### ISSUE TITLE
USER STORY: Anonymous feedback

### ISSUE THREAD

**Issue by JordanCH05** [JordanCH05/love-running#3]
## User Story

As a **user** I can **choose to hide my identity in the poll response** so that **I can provide anonymous feedback**

## Acceptance Criteria

* The option should be provided as a checkbox
*  The checkbox should be "checked" by default
*  The option should appear next to the submit button
*  After submitting the default submission confirmation should be adjusted to include the username

## Tasks

- [ ] Update the view: the poll design (HTML and CSS) to include the checkbox and to show the name to the submitter
- [ ] Create a new field in the model to track the username
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test functionality

**Comment by JordanCH05** [comment]
This is completed
